// ALTER TABLE tbl_customer
// MODIFY cust_cname VARCHAR(255) NULL DEFAULT NULL,
// MODIFY health_care_service VARCHAR(255) NULL DEFAULT NULL,
// MODIFY cust_country VARCHAR(100) NULL DEFAULT NULL,
// MODIFY cust_address TEXT NULL DEFAULT NULL,
// MODIFY cust_city VARCHAR(100) NULL DEFAULT NULL,
// MODIFY cust_state VARCHAR(100) NULL DEFAULT NULL,
// MODIFY cust_zip VARCHAR(50) NULL DEFAULT NULL,
// MODIFY cust_b_name VARCHAR(255) NULL DEFAULT NULL,
// MODIFY cust_b_cname VARCHAR(255) NULL DEFAULT NULL,
// MODIFY cust_b_phone VARCHAR(100) NULL DEFAULT NULL,
// MODIFY cust_b_country VARCHAR(100) NULL DEFAULT NULL,
// MODIFY cust_b_address TEXT NULL DEFAULT NULL,
// MODIFY cust_b_city VARCHAR(100) NULL DEFAULT NULL,
// MODIFY cust_b_state VARCHAR(100) NULL DEFAULT NULL,
// MODIFY cust_b_zip VARCHAR(50) NULL DEFAULT NULL,
// MODIFY cust_s_name VARCHAR(255) NULL DEFAULT NULL,
// MODIFY cust_s_cname VARCHAR(255) NULL DEFAULT NULL,
// MODIFY cust_s_phone VARCHAR(100) NULL DEFAULT NULL,
// MODIFY cust_s_country VARCHAR(100) NULL DEFAULT NULL,
// MODIFY cust_s_address TEXT NULL DEFAULT NULL,
// MODIFY cust_s_city VARCHAR(100) NULL DEFAULT NULL,
// MODIFY cust_s_state VARCHAR(100) NULL DEFAULT NULL,
// MODIFY cust_s_zip VARCHAR(50) NULL DEFAULT NULL,
// MODIFY cust_token VARCHAR(255) NULL DEFAULT NULL,
// MODIFY cust_image VARCHAR(255) NULL DEFAULT NULL,
// MODIFY cust_status VARCHAR(50) NULL DEFAULT NULL;


// ALTER TABLE tbl_customer
// DROP COLUMN cust_datetime,
// DROP COLUMN cust_timestamp;

// ALTER TABLE tbl_customer
// ADD COLUMN cust_datetime DATETIME NULL,
// ADD COLUMN cust_timestamp TIMESTAMP NULL;

